.TH "Point.hpp" 3 "Mon Mar 5 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Point.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPoint\fP"
.br
.RI "A Class implementing Labelled 3D, Unlabelled 3D, Labelled 2D, Unlabelled 2D \fBPoint\fP Abstract Data Types with appropriate methods\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
