.TH "Graph.hpp" 3 "Mon Mar 5 2018" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graph.hpp
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraph\fP"
.br
.RI "A \fBGraph\fP Class to model a 3D or a 2D view\&. Determine whether to use an Adjcancey List or Adjanceny Matrix representation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
