.TH "src/glwidget.cpp" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/glwidget.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'glwidget\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <QMainWindow>\fP
.br
\fC#include <QtGui>\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <QtOpenGL>\fP
.br
\fC#include <QGLWidget>\fP
.br
\fC#include <QGL>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'model\&.h'\fP
.br
\fC#include 'samplemodels\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
