.TH "src/mainwindow.cpp" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mainwindow.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'ui_mainwindow\&.h'\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <QtWidgets>\fP
.br
\fC#include <QFile>\fP
.br
\fC#include <QFileDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include <exception>\fP
.br
\fC#include 'model\&.h'\fP
.br
\fC#include 'model2d\&.h'\fP
.br
\fC#include 'samplemodels\&.h'\fP
.br
\fC#include 'glwidget\&.h'\fP
.br
\fC#include 'projectionx\&.h'\fP
.br
\fC#include 'projectiony\&.h'\fP
.br
\fC#include 'projectionz\&.h'\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBPI\fP   3\&.14159265"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define PI   3\&.14159265"

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
