.TH "src/model.cpp" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'model\&.h'\fP
.br
\fC#include <ios>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <QDebug>\fP
.br
\fC#include 'samplemodels\&.h'\fP
.br
\fC#include 'model2d\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
