.TH "src/model2d.h" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/model2d.h
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <string>\fP
.br
\fC#include <QGL>\fP
.br
\fC#include 'model\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProjection\fP"
.br
.ti -1c
.RI "class \fBModel2d\fP"
.br
.RI "creates the 2d model for a particular design by defining the necessary attributes "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
