.TH "src/projectionx.h" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/projectionx.h
.SH SYNOPSIS
.br
.PP
\fC#include <QWidget>\fP
.br
\fC#include <QGLWidget>\fP
.br
\fC#include 'model\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProjectionX\fP"
.br
.RI "defines the projectionX for the current design to be displayed using the model class "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
