.TH "src/samplemodels.cpp" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/samplemodels.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'samplemodels\&.h'\fP
.br
\fC#include <math\&.h>\fP
.br
\fC#include 'model\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
