.TH "src/samplemodels.h" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/samplemodels.h
.SH SYNOPSIS
.br
.PP
\fC#include 'model\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSampleModels\fP"
.br
.RI "defines the templates for the software including other necessary designs for base display like the axes "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
