.TH "src/window2d.cpp" 3 "Fri Apr 6 2018" "CAD Software" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/window2d.cpp
.SH SYNOPSIS
.br
.PP
\fC#include 'window2d\&.h'\fP
.br
\fC#include 'ui_window2d\&.h'\fP
.br
\fC#include 'model\&.h'\fP
.br
\fC#include 'samplemodels\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for CAD Software from the source code\&.
